//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEISURE_Kursach.ado
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LEISURE_KursachEntities : DbContext
    {
        public LEISURE_KursachEntities()
            : base("name=LEISURE_KursachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Activity_Type> Activity_Type { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Place_Type> Place_Type { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
