//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEISURE_Kursach.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual User User { get; set; }
    }
}
