//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ado
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LEISURE_KursachEntities1 : DbContext
    {
        public LEISURE_KursachEntities1()
            : base("name=LEISURE_KursachEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Activity_Type> Activity_Type { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Place_Type> Place_Type { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Status_Request> Status_Request { get; set; }
    }
}
