//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Activity = new HashSet<Activity>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ID_Place { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public System.TimeSpan TimeStart { get; set; }
        public Nullable<double> Price { get; set; }
        public string Description { get; set; }
        public byte[] Photo { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_Type { get; set; }
        public string ContactInfo { get; set; }
        public Nullable<int> ID_Status { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activity { get; set; }
        public virtual Activity_Type Activity_Type { get; set; }
        public virtual Place Place { get; set; }
        public virtual Status_Request Status_Request { get; set; }
    }
}
