//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public Nullable<int> ID_Client { get; set; }
        public Nullable<int> ID_Place { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Review_Message { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Place Place { get; set; }
    }
}
